var traduction = {
  0: {
    LANG: "FR",
    QUICK: "JOUER",
    DAY: "DEFI DU JOUR",
    CUSTOM: "PARTIE PERSONNALISEE",
    ABOUT: "A PROPOS",
    LOAD: "CHARGER",
    ERROR_UNABLE: "IMPOSSIBLE DE CHARGER UNE PARTIE",
    COMPETITIVE: "COMPETITIF",
    SOLO: "SOLO / COOP",
    CLASSIC: "Classique",
    EXTREME: "Extrême",
    NIGHTMARE: "Cauchemar",
    CLASSICSUB: "",
    EXTREMESUB: "(Voir la règle)",
    NIGHTMARESUB: "(Voir la règle)",
    EASY: "Facile",
    MEDIUM: "Moyen",
    HARD: "Difficile",
    V4: "4 vérificateurs",
    V5: "5 vérificateurs",
    V6: "6 vérificateurs",
    PLAY: "GENERER",
    LOADING: "CHARGEMENT...",
    CHECKCODE: "TESTER UN CODE",
    INPUTCODE: "SAISIR LE CODE",
    TESTCODE: "VERIFICATION",
    FALSECODE: "CE N'EST PAS LE CODE !!!",
    YOUWIN: "VICTOIRE !!!",
    CANCEL: "RETOUR",
    SOLUTION: "SOLUTION",
    BACK: "RETOUR",
    SHOW_SOLUTION: "VOIR LA SOLUTION ?",
    YES: "OUI",
    NO: "NON",
    CODE: "CODE",
    SHEET: "FEUILLE DE NOTES",
    SEARCH: "# PARTIE",
    STEP1: "Mode",
    STEP2: "Difficulté",
    STEP3: "Longueur",
    CRITERIA: "Cartes Critères",
    CRITERIADOUBLE: "Cartes Critères (2 par vérificateur)",
    CRITERIAMIXED: "Cartes Critères (mélangées)",
    VERIFIER: "Cartes Vérification"
  },
  1: {
    LANG: "EN",
    QUICK: "PLAY",
    DAY: "GAME OF THE DAY",
    CUSTOM: "CUSTOM GAME",
    ABOUT: "ABOUT",
    LOAD: "LOAD",
    ERROR_UNABLE: "UNABLE TO LOAD GAME",
    COMPETITIVE: "COMPETITIVE",
    SOLO: "SOLO / COOP",
    CLASSIC: "Classic",
    EXTREME: "Extreme",
    NIGHTMARE: "Nightmare",
    CLASSICSUB: "",
    EXTREMESUB: "(See rulebook)",
    NIGHTMARESUB: "(See rulebook)",
    EASY: "Easy",
    MEDIUM: "Standard ",
    HARD: "Hard",
    V4: "4 cards",
    V5: "5 cards",
    V6: "6 cards",
    PLAY: "GENERATE",
    LOADING: "LOADING...",
    CHECKCODE: "TEST A CODE",
    INPUTCODE: "INPUT THE CODE",
    TESTCODE: "VERIFICATION",
    FALSECODE: "IT'S NOT THE CODE!!!",
    YOUWIN: "VICTORY!!!",
    CANCEL: "BACK",
    SOLUTION: "SOLUTION",
    BACK: "BACK",
    SHOW_SOLUTION: "SHOW SOLUTION?",
    YES: "YES",
    NO: "NO",
    CODE: "CODE",
    SHEET: "NOTE SHEET",
    SEARCH: "# GAME",
    STEP1: "Mode",
    STEP2: "Difficulty",
    STEP3: "Duration",
    CRITERIA: "Criteria Cards",
    CRITERIADOUBLE: "Criteria Cards (2 on each verifier)",
    CRITERIAMIXED: "Criteria Cards (mixed)",
    VERIFIER: "Verification Cards"
  }
};

export default traduction;
